- type: gameMapPool
  id: DefaultStarlightMapPool
  maps:
  - StarlightBagel
  - StarlightBox
  - StarlightCog
  - StarlightFland
  - StarlightMarathon
  - StarlightMeta
  - StarlightOasis
  - StarlightOmega
  - StarlightPacked
  - StarlightHotel
