- type: latheRecipe
  id: CartridgePistolRubber
  result: CartridgePistolRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeMagnumRubber
  result: CartridgeMagnumRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 5
    Steel: 5

- type: latheRecipe
  id: CartridgeLightRifleRubber
  result: CartridgeLightRifleRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5

- type: latheRecipe
  id: CartridgeRifleRubber
  result: CartridgeRifleRubber
  category: Ammo
  completetime: 2
  materials:
    Plastic: 10
    Steel: 5
    
- type: latheRecipe
  id: MagazineBoxPistolRubber
  result: MagazineBoxPistolRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300
    
- type: latheRecipe
  id: MagazineBoxMagnumRubber
  result: MagazineBoxMagnumRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 300
    
- type: latheRecipe
  id: MagazineBoxRifleRubber
  result: MagazineBoxRifleRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600
    
- type: latheRecipe
  id: MagazineBoxLightRifleRubber
  result: MagazineBoxLightRifleRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600
    
- type: latheRecipe
  id: ShellShotgunBeanbag
  result: MagazineBoxLightRifleRubber
  category: Ammo
  completetime: 5
  materials:
    Steel: 350
    Plastic: 600