- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 #20 hrs
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 54000 #15 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Medical
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    eyes: ClothingEyesHudMedSec
    ears: ClothingHeadsetSecurity
    neck: ClothingNeckTieRed
    pocket1: WeaponPistolMk58
    mask: ClothingMaskBreathMedicalSecurity
    id: BrigmedicPDA
    gloves: ClothingHandsGlovesNitrile
  storage:
    back:
    - Flash
    - MagazinePistol
