- type: job
  id: Magistrate
  name: job-name-magistrate
  description: job-description-magistrate
  playTimeTracker: JobMagistrate
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 180000 #50 hrs
  startingGear: MagistrateGear
  icon: "JobIconMagistrate"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  setPreference: true
  access:
  - Magistrate
  - Bar
  - Kitchen
  - Hydroponics
  - Janitor
  - Theatre
  - Chapel
  - Lawyer
  - Brig
  - Security
  - Medical
  - Research
  - Engineering
  - Cargo
  - Salvage
  - Command
  extendedAccess:
  - Hydroponics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: MagistrateGear
  equipment:
    jumpsuit: MagistrateUniformSuit
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterRobesJudge
    id: MagistratePDA
    ears: ClothingHeadsetAltCommand
    head: ClothingHeadHatPwig
    pocket1: Flash
  storage:
    back:
#    - RubberStampMagistrate
    - ClothingNeckLawyerbadge
    - GavelHammer
    - GavelBlock