- type: listing
  id: VendorDoubleStunbaton
  productEntity: DoubleStunbaton
  cost:
    NTCredit: 556
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition
  
- type: listing
  id: VendorPurpleStunbaton
  productEntity: PurpleStunbaton
  cost:
    NTCredit: 376
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition

- type: listing
  id: WeaponPistolN1987
  productEntity: WeaponPistolN1987
  cost:
    NTCredit: 600
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 3
  - !type:BuyerAccessCondition
  
- type: listing
  id: MagazineMagnumPractice
  productEntity: MagazineMagnumPractice
  cost:
    NTCredit: 100
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 6
  - !type:BuyerAccessCondition

- type: listing
  id: ClothingHandsGlovesCombat
  productEntity: ClothingHandsGlovesCombat
  cost:
    NTCredit: 399
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition
