name: Update Changelog

on:
  push:
    branches:
      - Starlight

permissions:
  contents: write
  pull-requests: read

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pyyaml PyGithub

      - name: Get Pull Request Number
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "Current commit SHA: $COMMIT_SHA"

          # Создаем GraphQL запрос
          QUERY='
          {
            repository(owner: "'${{ github.repository_owner }}'", name: "'${{ github.event.repository.name }}'") {
              object(oid: "'$COMMIT_SHA'") {
                ... on Commit {
                  associatedPullRequests(first: 1) {
                    nodes {
                      number
                    }
                  }
                }
              }
            }
          }'

          # Выполняем запрос
          PR_DATA=$(curl -s -H "Authorization: bearer $GITHUB_TOKEN" -X POST -d '{"query": "'"$QUERY"'"}' https://api.github.com/graphql)
          
          PR_NUMBER=$(echo "$PR_DATA" | python -c "import sys, json; data=json.load(sys.stdin); nodes = data.get('data', {}).get('repository', {}).get('object', {}).get('associatedPullRequests', {}).get('nodes', []); print(nodes[0]['number'] if nodes else '')")
          
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR associated with commit $COMMIT_SHA"
            exit 0
          fi

          echo "PR Number: $PR_NUMBER"
          echo "::set-output name=PR_NUMBER::$PR_NUMBER"

      - name: Parse PR and Update Changelog
        if: steps.get_pr.outputs.PR_NUMBER != ''
        env:
          CHANGELOG_FILE_PATH: 'Resources/Changelog/ChangelogStarlight.yml'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.get_pr.outputs.PR_NUMBER }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ./Tools/_Starlight/update_changelog.py

      - name: Commit and push changes
        if: steps.get_pr.outputs.PR_NUMBER != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "Resources/Changelog/ChangelogStarlight.yml"
          git commit -m "Update changelog for PR #${{ steps.get_pr.outputs.PR_NUMBER }} [skip ci]"
          git push origin HEAD:Starlight
