name: Update Changelog

on:
  push:
    branches:
      - Starlight

permissions:
  contents: write
  pull-requests: read

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pyyaml PyGithub requests

      - name: Get Pull Request Number
        id: get_pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "Current commit SHA: $COMMIT_SHA"

          # Поиск PR, связанного с этим коммитом
          PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=sha:$COMMIT_SHA+is:merged+is:pr")

          PR_NUMBER=$(echo "$PR_DATA" | python -c "import sys, json; print(json.load(sys.stdin)['items'][0]['number'])")

          echo "PR Number: $PR_NUMBER"

          echo "::set-output name=PR_NUMBER::$PR_NUMBER"

      - name: Parse PR and Update Changelog
        env:
          CHANGELOG_FILE_PATH: 'Resources/Changelog/ChangelogStarlight.yml'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ steps.get_pr.outputs.PR_NUMBER }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python ./Tools/_Starlight/update_changelog.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "Resources/Changelog/ChangelogStarlight.yml"
          git commit -m "Update changelog for PR #${{ steps.get_pr.outputs.PR_NUMBER }} [skip ci]"
          git push origin HEAD:Starlight
