name: Notify Discord on Map PR

on:
  pull_request:
    types: [labeled]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Labels
        id: check-label
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = pr.labels.map(label => label.name);
            if (labels.includes("Changes: Map")) {
              core.setOutput("send_notification", "true");
            } else {
              core.setOutput("send_notification", "false");
            }
      - name: Send Discord Notification
        if: steps.check-label.outputs.send_notification == 'true'
        run: |
          JSON_PAYLOAD=$(jq -n --arg title "🗺️ New PR with map changes!" \
              --arg url "${{ github.event.pull_request.html_url }}" \
              --arg pr_title "${{ github.event.pull_request.title }}" \
              --arg pr_desc "${{ github.event.pull_request.body && github.event.pull_request.body || 'No description provided' }}" \
              --arg author "${{ github.event.pull_request.user.login }}" \
              --arg repo "${{ github.repository }}" \
              --arg pr_number "#${{ github.event.pull_request.number }}" \
              '{
                "embeds": [{
                  "title": $title,
                  "description": $pr_title,
                  "url": $url,
                  "color": 16776960,
                  "fields": [
                    {"name": "📝 Description", "value": $pr_desc, "inline": false},
                    {"name": "👤 Author", "value": $author, "inline": true},
                    {"name": "📂 Repository", "value": $repo, "inline": true},
                    {"name": "🔢 PR Number", "value": $pr_number, "inline": true}
                  ],
                  "footer": {
                    "text": "GitHub Actions - Space Station 14",
                    "icon_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                  },
                  "timestamp": "${{ github.event.pull_request.created_at }}"
                }]
              }')

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$JSON_PAYLOAD" \
               ${{ secrets.DISCORD_MAPPING_WEBHOOK_URL }}
